### ISSUE TITLE
Feature Request - Percentage based error thresholds

### ISSUE THREAD

**Issue by ryhinchey** [fastify/fastify-circuit-breaker#31]
## 🚀 Feature Proposal

Add support for percentage based error thresholds.  Happy to work on this if it's something that'd be a good addition to the library.

## Motivation

Often a threshold percentage makes more sense and is what developers might be used to if they've used a library like Oppossum before.  

## Example

I think we could reuse the existing `threshold` option.  Pass an integer to keep the existing behavior or pass a float to enable a percentage based calculation.

```js
fastify.register(require('fastify-circuit-breaker'), {
  threshold: 0.5 // enables percentage based calculation
})
```

**Comment by mcollina** [comment]
Would you like to send a PR to implement this? Would this be per-route?

**Comment by ryhinchey** [comment]
Yes - I'd be happy to implement this.  My thinking is it'd be per route or applied to all routes just like `threshold` is currently
